In [1]:
%matplotlib inline
import numpy as np 
import configparser
import matplotlib.pyplot as plt
config = configparser.ConfigParser()
import os
import csv
import sys,importlib
from pathlib import Path

sys.path.insert(0, '../../gui')
# import larch_score
import EXAFS_Analysis
import larch_score

In [7]:
!pwd

/Users/andy/projects/EXAFS_Neo/tests/cu_test_files


In [3]:
paths = [1,2,3,5,6,10,14,16,28,30,36,40,42]



In [87]:
importlib.reload(larch_score)
importlib.reload(EXAFS_Analysis)

params = {}
params['base'] = Path(os.getcwd()).parent.parent
# print(params['base'])
params['Kmin'] = 3.0
params['Kmax'] = 17.0
params['kweight'] = 2.0
params['deltak'] = 0.05
params['rbkg'] = 1.2
params['bkgkw'] = 1.0
params['bkgkmax'] = 25.0
params['front'] = ["tests/cu_test_files/cu_paths/path_75/feff"]
params['CSV'] = "tests/cu_test_files/cu_paths/cu_10k.xmu"
params['optimize'] = 'False'
params['series_index'] = 0
params['series'] = False
dirs = 'cu_results'

# larch_score.larch_init(params['CSV'],params)

Test_Result = EXAFS_Analysis.EXAFS_Analysis(paths,dirs,params)

Test_Result.extract_data()

Test_Result.larch_init()
Test_Result.larch_score()
# Test_Result.plot("Cu")


Test_Result.individual_fit()

cu_results
Individual Path: False
[[ 0.721429  0.414286  0.003    -0.018571]
 [ 0.641429  0.414286  0.009429 -0.03    ]
 [ 0.455714  0.414286  0.007    -0.01    ]
 [ 0.797143  0.414286  0.007143  0.005714]
 [ 0.527143  0.414286  0.008286  0.017143]
 [ 0.678571  0.414286  0.009143  0.044286]
 [ 0.425714  0.414286  0.008571 -0.05    ]
 [ 0.562857  0.414286  0.008857  0.025714]
 [ 0.632857  0.414286  0.01     -0.02    ]
 [ 0.351429  0.414286  0.009143 -0.041429]
 [ 0.332857  0.414286  0.008429  0.011429]
 [ 0.535714  0.414286  0.007571 -0.004286]
 [ 0.67      0.414286  0.007286 -0.044286]]
Number of Components: 1
Path 1 0.721429 0.414286 0.003 2.534129
Path 2 0.641429 0.414286 0.009429 3.58
Path 3 0.455714 0.414286 0.007 3.8190000000000004
Path 5 0.797143 0.414286 0.007143 4.427014
Path 6 0.527143 0.414286 0.008286 4.780443
Path 10 0.678571 0.414286 0.009143 5.149585999999999
Path 14 0.425714 0.414286 0.008571 5.0553
Path 16 0.562857 0.414286 0.008857 5.733614
Path 28 0.632857 0.414286 0.

In [33]:
Test_Result.chir2

0.763548

In [83]:

best_Fit_r = Test_Result.best_Fit_r

best_Fit_r[0]

[0.721429,
 0.414286,
 0.003,
 2.534129,
 12.0,
 2.0,
 [('Cu', 29, 0, 63.546, '-0.0000', '-0.0000', '-0.0000'),
  ('Cu', 29, 1, 63.546, '-0.0000', '-1.8050', '-1.8050')]]

In [89]:
Test_Result.bestFit_mat.shape


(13, 4)

In [86]:
type(best_Fit_r[0][6])

list

In [88]:
Test_Result.construct_latex_table(print_table=True)

[[0.721429, 0.414286, 0.003, 2.534129, 12.0, 2.0, [('Cu', 29, 0, 63.546, '-0.0000', '-0.0000', '-0.0000'), ('Cu', 29, 1, 63.546, '-0.0000', '-1.8050', '-1.8050')]], [0.641429, 0.414286, 0.009429, 3.58, 6.0, 2.0, [('Cu', 29, 0, 63.546, '-0.0000', '-0.0000', '-0.0000'), ('Cu', 29, 1, 63.546, '-0.0000', ' 3.6100', '-0.0000')]], [0.455714, 0.414286, 0.007, 3.8190000000000004, 48.0, 3.0, [('Cu', 29, 0, 63.546, '-0.0000', '-0.0000', '-0.0000'), ('Cu', 29, 1, 63.546, ' 1.8050', '-0.0000', '-1.8050'), ('Cu', 29, 1, 63.546, ' 1.8050', '-1.8050', '-0.0000')]], [0.797143, 0.414286, 0.007143, 4.427014, 24.0, 2.0, [('Cu', 29, 0, 63.546, '-0.0000', '-0.0000', '-0.0000'), ('Cu', 29, 1, 63.546, '-3.6100', ' 1.8050', '-1.8050')]], [0.527143, 0.414286, 0.008286, 4.780443, 48.0, 3.0, [('Cu', 29, 0, 63.546, '-0.0000', '-0.0000', '-0.0000'), ('Cu', 29, 1, 63.546, '-0.0000', '-1.8050', ' 1.8050'), ('Cu', 29, 1, 63.546, '-1.8050', ' 1.8050', '-0.0000')]], [0.678571, 0.414286, 0.009143, 5.149585999999999, 24.